/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package subtitle.translator;

import subtitle.translator.GCP_basic_translator.TikaParser;
import subtitle.translator.GCP_basic_translator.Translator;

import java.io.*;


public class App {
    public static void main(String[] args) {
        Translator translator = new Translator("translation-basic-266904", "zh");
        try {
//            String test = translator.translate("You'll learn how Kotlin expression");
//            BufferedWriter writer = new BufferedWriter(new FileWriter("test-output.txt", true));
//            writer.append('\n');
//            writer.append(test);
//            writer.close();
//            System.out.println("Translated text:" + test);

            TikaParser tikaParser = new TikaParser();
            tikaParser.test();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
