/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GCP_Translation;

import java.io.*;


public class App {
    public static void main(String[] args) {
        Translator translator = new Translator();
        try {
            String test = translator.translate("You'll learn how Kotlin expression");
            BufferedWriter writer = new BufferedWriter(new FileWriter("test.txt", true));
            writer.append('\n');
            writer.append(test);
            writer.close();
        } catch (Exception e) {
            System.out.println();
        }

    }
}
